[es]
  title = "HotspotCepeda"
  languageName = "Español"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/es"

[en]
  title = "HotspotCepeda"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"
