[[main]]
  identifier = "sitio"
  name = "Sitio"
  url = "sitio"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archivo"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "Pt"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "fotos"
  name = "Fotos"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "fotos"
  name = "Red"
  url = "gallery/red"

[[main]]
  parent = "fotos"
  name = "Paisaje"
  url = "gallery/paisaje"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5

[[main]]
  identifier = "showcase"
  name = "Escaparate"
  url = "showcase"
  weight = 6

[[main]]
  identifier = "publication"
  name = "Publicaciones"
  url = "publication"
  weight = 7

[[main]]
  identifier = "clima"
  name = "Clima"
  url = "http://cepeda.qui.guifi.net/weewx/index.html"
  weight = 8
